### PR TITLE
remove deprecate call in InferenceATF

### PR DESCRIPTION
**Pull request by CharlesZ-Chen**
This PR depends on changes in the PR against to the changes in checker-framework
https://github.com/typetools/checker-framework/pull/848

Should check this PR after merging the changes in checker-framework merged in our pascaliUWat repo.

### CODE REVIEW

**Comment by topnessman** [comment]
Do you mean this pull request depends on a pending pull request #848 to typetools/checker-framework?

**Comment by CharlesZ-Chen** [comment]
Yes, this PR depends on the PR #848 in typetools/checker-framework or the PR #1 in pascaliUWat/checker-framewrok.

The PR #848 in typetools/checker-framework is a specific PR that contains only the changes on ATF, which this PR depends on.

The PR #1 in pascaliUWat/checker-frameowrk is a huge PR that contains the changes on ATF and also other changes.

Merged either one first, and then we could check this PR.

**Comment by topnessman** [comment]
But what I have seen is that #848 to typetools contains much more commits than #1 to pascaliUWat. And #1 to pascaliUWat is already merged. For me, it seems that this pull request doesn't merely depends on #1 to pascaliUWat?

**Comment by CharlesZ-Chen** [comment]
It's [#1 in pascaliUWat/**checker-frameowrk**](https://github.com/pascaliUWat/checker-framework/pull/1). Not #1 in checker-framework-inference.

**Pull request merged**
