### PR TITLE
simple but may not proper quick fix.

### PR DESCRIPTION
**Pull request by CharlesZ-Chen**
This PR is made for discussion purpose on how to have a proper fix on the bug exposed by dyn4j.

corresponding minimun test case:
```java

class Bar<T> {
T t;
}

class Foo extends Bar<Object> {

}

public class BodyTest {
public void removeFixtureFound(Foo foo) {
if (foo.t == null) {}
}
}
```

@wmdietl @Jianchu

### CODE REVIEW

**Comment by wmdietl** [comment]
Please add the test case to the test suite. This will ensure that your change actually fixes it and will prevent the bug from coming back.

**Comment by CharlesZ-Chen** [comment]
Hi Prof. Dietl, could we add "isHack=true" in test suite? Currently my simple fix only works under hack mode, and it will failed when running it as a junit test without "isHace=true"..

**Comment by wmdietl** [comment]
Can you add a new subdirectory with tests that require hack-mode and add a new test driver that enables hack mode.
We shouldn't enable it for all tests, as most work without hack mode.
We should work on having as few tests that require hack mode as possible.

**Comment by CharlesZ-Chen** [comment]
Sure. I have a quick question when adding a new CF Test class:

Do we have a "general" checker ( like in solver we have `DebugSolver` as a "general" solver) to running tests that apply to all checkers that extends `InferenceChecker`?

I tried directly using `InferenceChecker` but I get a NullpointerException :
```
 [junit] 1 unexpected diagnostic was found:
    [junit] :-1: other: error: SourceChecker.typeProcessingStart: unexpected Throwable (NullPointerException)
    [junit]   Exception: java.lang.NullPointerException; Stack trace: checkers.inference.InferenceChecker.initChecker(InferenceChecker.java:10)
    [junit]   org.checkerframework.framework.source.SourceChecker.typeProcessingStart(SourceChecker.java:827)
    [junit]   org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:183)
    [junit]   com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
    [junit]   com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
    [junit]   com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
    [junit]   com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
    [junit]   com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
```

**Comment by CharlesZ-Chen** [comment]
@Jianchu Jason told me I should use `OstrustedChecker` as default implementation. Thus I use `Ostrusted` in my new test class.

**Comment by CharlesZ-Chen** [comment]
This fix is not proper. A more proper fix is made in Checker Framework: 
- https://github.com/opprop/checker-framework/pull/5

**Pull request closed without merging**
